### PR TITLE
Feature/Aditional fields

### PR DESCRIPTION
**Pull request by paganotoni**
Will allow adding custom fields to the generated user model, related with #1

### CODE REVIEW

**Comment by paganotoni** [comment]
I feel some of the work in here could trigger some stories in pop, p.e duplicate field validation, and the possibility to avoid adding validation when generating a model

**Comment by paganotoni** [comment]
@markbates i think this one is ready to be tested @BryanMoslo if you want to give it a shot, i will also appreciate your input.

**Review by markbates — CHANGES_REQUESTED** [review]
I don’t suppose I can convince you to move that source operator stuff to genny, can I? It would be really useful there.

**Comment by paganotoni** [comment]
I think it makes sense, while i was working on this feature i considered this could be useful for other source modifications we do in buffalo hence why i added it as a separate struct, so, yes, i will move it there.

**Comment by paganotoni** [comment]
@markbates after thinking about it, i wonder if we could do:

1. moving it to be its own package inside this package
2. adding tests for that package
3. moving that package  to `genny`
4. moving `buffalo-auth` to use `genny` and remove operator from it

1 and 2 may be required to merge this PR but part of me doesn't want to hold this PR it because of `genny`.

**Comment by markbates** [comment]
That sounds like a good plan. We can rewrite them, and move them, as file transformers later when we rewrite this plugin.

**Comment by paganotoni** [comment]
@markbates 1 and 2 completed, we can merge this one and then work on the genny migration, i'm willing to work in that one, i'll also use the new inflection package if possible.

**Comment by paganotoni** [comment]
(Also added some documentation to see if i convince you of the merge :))

**Review by markbates — APPROVED** [review]

**Comment by markbates** [comment]
Love it. Now can you convert it to Genny? :) I would also love to see each of those transformers to get converted to.

**Comment by paganotoni** [comment]
Yes, thats next in my list

**Pull request merged**
