### PR TITLE
use gobuffalo version of pop

### PR DESCRIPTION
**Pull request by robbyoconnor**

### CODE REVIEW

**Comment by markbates** [comment]
Can you also update the validate package from markbates to go buffalo?

**Comment by robbyoconnor** [comment]
Sure.

**Comment by robbyoconnor** [comment]
Done.

**Review by markbates — APPROVED** [review]

**Comment by markbates** [comment]
Thanks!

**Comment by robbyoconnor** [comment]
What would also be awesome -- and I might do it - is if it allowed for me to have sayyy a JSON API

**Pull request merged**
