### PR TITLE
Organizes routes a bit and avoids overriding index.html

### PR DESCRIPTION
**Pull request by paganotoni**
This is related with #47.

### CODE REVIEW

**Review by mclark4386 — APPROVED** [review]
Looks good to me!

**Comment by AtomicNibble** [comment]
This breaks the tests as some of the tests are still checking for /signin etc.

**Comment by paganotoni** [comment]
Taking a look. Thanks for the heads up @AtomicNibble

**Comment by paganotoni** [comment]
@AtomicNibble fixed this one in #65, thanks for the heads up.

**Comment by AtomicNibble** [comment]
Thanks.

**Pull request merged**
